import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import Provider from "@/util/Providers";

import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import CartProvider from "@/util/cart";

export const metadata: Metadata = {
  title: "MKS Sistemas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <StyledComponentsRegistry>
          <CartProvider>
            <Header />
            <Provider>
              {children}
            </Provider>
            <Footer />
          </CartProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
